version: "3.3"

services:
  blog:
    image: jekyll/jekyll:4.0.0
    command: jekyll serve --force_polling --drafts --livereload --trace
    ports:
      - "4000:4000"
    volumes:
      - ".:/srv/jekyll"

